create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  city text not null,
  country text not null,
  address text,
  bedrooms integer default 0,
  bathrooms integer default 0,
  area_sqm numeric,
  image_url text,
  created_at timestamptz default now()
);